import asyncio
import json
import time
from google.adk.tools.tool_context import ToolContext
from ...adk_common.dtos.generated_media import GeneratedMedia
from ...adk_common.utils import utils_agents, utils_gcs
from ...adk_common.utils.utils_logging import Severity, log_message
from ...state import (
    PRODUCT_COMPANY_NAME_STATE_KEY,
)
from ...utils.utils_gcs import get_public_url, set_output_folder
from ...schema import NanomationPlan
from ..media import _generate_gemini_image, _generate_single_veo_clip
from .utils import client, types

def generate_slide_animation_plan(tool_context: ToolContext, slide_topic: str, duration_seconds: int = 5) -> dict:
    """Generates a NanomationPlan (JSON) for a specific slide topic using dynamic segments.
    """
    log_message(f"Planning nanomation for: {slide_topic}...", Severity.INFO)
    
    company_name = tool_context.state.get(PRODUCT_COMPANY_NAME_STATE_KEY, "Brand")
    
    prompt = (
        f"You are a Senior Motion Designer for {company_name}.\n"
        f"Goal: Plan a multi-segment video animation (Nanomation) for the topic: '{slide_topic}'.\n\n"
        f"CONCEPT:\n"
        f"- You must determine the logical number of segments based on the slide's content and voiceover length (typically 2 to 4 segments).\n"
        f"- For each segment (phase), you will provide a starting 'image_prompt', a 'motion_prompt', and a 'duration_seconds'.\n"
        f"- The video will be generated by smoothly interpolating between the image generated for segment N and the image generated for segment N+1.\n"
        f"- Target high consistency: The background and core subjects must remain stable while specific actions progress.\n\n"
        f"Output ONLY valid JSON matching this schema:\n"
        f"{{\n"
        f"  \"target\": \"[High-level description of the entire animated sequence]\",\n"
        f"  \"progression_type\": \"linear\",\n"
        f"  \"phases\": [\n"
        f"    {{\"description\": \"[Description of segment 1]\", \"image_prompt\": \"[Detailed prompt for Imagen 3]\", \"motion_prompt\": \"[Cinematic motion directive]\", \"duration_seconds\": 4}},\n"
        f"    {{\"description\": \"[Description of segment 2]\", \"image_prompt\": \"[End of seg 1/Start of seg 2]\", \"motion_prompt\": \"[Cinematic motion directive]\", \"duration_seconds\": 4}},\n"
        f"    ...\n"
        f"  ],\n"
        f"  \"topic\": \"{slide_topic}\"\n"
        f"}}"
    )

    try:
        response = client.models.generate_content(
            model="gemini-3.1-pro-preview",
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.7,
                response_mime_type="application/json",
            ),
        )
        return json.loads(response.text)
    except Exception as e:
        log_message(f"Nanomation planning failed: {e}", Severity.ERROR)
        return {"error": str(e)}

async def execute_slide_animation(tool_context: ToolContext, animation_plan: dict) -> dict:
    """Executes a NanomationPlan by generating static keyframes and interpolating them using Veo.
    """
    current_output_folder = set_output_folder(tool_context)
    log_message("Executing nanomation sequence...", Severity.INFO)

    try:
        plan = NanomationPlan.model_validate(animation_plan)
    except Exception as e:
        return {"status": "error", "details": f"Invalid plan: {e}"}

    if not plan.phases:
        return {"status": "error", "details": "No phases found in animation plan."}

    # 1. Generate static images (keyframes)
    images_bytes = []
    image_uris = []
    
    for i, phase in enumerate(plan.phases):
        log_message(f"Generating keyframe {i+1}/{len(plan.phases)}: {phase.description}", Severity.INFO)
        
        refs = [images_bytes[-1]] if images_bytes else []
        img_bytes = await _generate_gemini_image(phase.image_prompt, refs, label=f"keyframe_f{i+1}", aspect_ratio="16:9")
        
        if not img_bytes:
            log_message(f"Failed to generate keyframe {i+1}", Severity.ERROR)
            return {"status": "error", "details": f"Failed to generate keyframe {i+1}."}
            
        images_bytes.append(img_bytes)
        
        media = GeneratedMedia(filename=f"keyframe_{int(time.time())}_{i+1}.png", mime_type="image/png", media_bytes=img_bytes)
        saved = await utils_agents.save_to_artifact_and_render_asset(
            asset=media, context=tool_context, save_in_gcs=True, save_in_artifacts=False, gcs_folder=current_output_folder
        )
        phase.image_url = utils_gcs.normalize_to_gs_bucket_uri(saved.gcs_uri)
        image_uris.append(phase.image_url)

    # 2. Generate Veo clips using interpolation
    veo_tasks = []
    for i, phase in enumerate(plan.phases):
        start_uri = image_uris[i]
        end_uri = image_uris[i+1] if (i + 1) < len(image_uris) else None
        
        duration = phase.duration_seconds or 4
        motion = phase.motion_prompt or "Cinematic smooth motion"
        
        veo_tasks.append(_generate_single_veo_clip(motion, start_uri, clip_duration=duration, end_frame_gcs_uri=end_uri, label=f"nanomation_seg_{i+1}"))
    
    log_message(f"Triggering {len(veo_tasks)} Veo generations in parallel...", Severity.INFO)
    veo_results = await asyncio.gather(*veo_tasks)
    
    clips = [res for res in veo_results if res]
    if not clips:
        return {"status": "error", "details": "Veo generation failed for all segments."}
        
    # 3. Stitch the clips together
    log_message(f"Stitching {len(clips)} video segments...", Severity.INFO)
    from ...shared_infra.utils_media import stitch_videos
    stitched_video = stitch_videos(clips) if len(clips) > 1 else clips[0]
    
    if not stitched_video:
        return {"status": "error", "details": "Failed to stitch video clips."}
        
    final_media = GeneratedMedia(filename=f"nanomation_stitched_{int(time.time())}.mp4", mime_type="video/mp4", media_bytes=stitched_video)
    saved_final = await utils_agents.save_to_artifact_and_render_asset(
        asset=final_media, context=tool_context, save_in_gcs=True, save_in_artifacts=False, gcs_folder=current_output_folder
    )
    
    return {
        "status": "success",
        "message": f"Nanomation video '{plan.topic}' generated successfully.",
        "plan": plan.model_dump(),
        "video_url": get_public_url(saved_final.gcs_uri)
    }
